name: 'Child Issue'
description: 'Creates a Child Issue'
author: 'LeakyBucket'
inputs: 
  github-token:
    description: 'GitHub Access Token.  Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  org:
    description: 'GitHub organization'
    required: true
  project:
    description: 'GitHub repository'
    required: true
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Issue body'
  milestone:
    description: 'Associated milestone (id)'
runs:
  using: 'docker'
  image: 'Dockerfile'