[package]
authors = ["Glen Holcomb"]
edition = "2018"
name = "child_issue"
version = "0.1.0"

[[bin]]
name = "child_issue"
path = "src/main.rs"

[dependencies]
clap = "*"
# hubcaps = "*"
hubcaps = { git = "https://github.com/softprops/hubcaps" }
tokio = "*"
hyper = "*"